cache:
  path: ./.fastrag
  lifespan: 1d
steps:
  fetching:
    # - strategy: Path
    #   params:
    #     path: ./resources/test/
    # - strategy: SitemapXML
    #   params:
    #     url: https://agrospai.udl.cat/sitemap.xml
    #     regex:
    #       - https?://[^/]+/docs/
    # - strategy: URL
    #   params:
    #     url: https://x.com
    - strategy: Crawling
      params:
        url: https://agrospai.udl.cat
        workers: 5
        depth: 3
        delay: 0
  parsing:
    - strategy: HtmlParser
      params:
        use:
          - Sitemap
          - Crawling
    # - strategy: FileParser
    #   params:
    #     use:
    #       - Path
  chunking:
    - strategy: RecursiveTextSplitter
      params:
        chunk_size: 500
  embedding:
    - strategy: OpenAI-Simple
      params:
        model: nomic-embed-text:latest
        api_key: ${API_KEY}
        url: https://chat.agrospai.udl.cat/api/
  benchmarking:
    - strategy: ...
      params:
        test: asdsa
