cache:
  path: ./cache
  time: 5m
steps:
  - sources:
      - strategy: URL
        params:
          url: ...
      - strategy: Path
        params:
          path: ...
      - strategy: Sitemap
        params:
          path: https://agrospai.udl.cat/sitemap.xml
  - parsing: ...
  - chunking:
      strategy: RecursiveTextSplitter
      params:
        chunk_size: 500
  - embedding:
      strategy: SimpleOpenAIAPI
      params:
        model: nomic-embed-text:latest
        api_key: ${API_KEY}
        url: chat.agrospai.udl.cat/api/
  - benchmarking:
      strategy:
      params:
