cache:
  path: ./.fastrag
  time: 5m
steps:
  sources:
    - strategy: URL
      params:
        url: https://chatgpt.com/
    - strategy: Path
      params:
        path: ./resources/test/
    - strategy: SitemapXML
      params:
        url: https://agrospai.udl.cat/sitemap.xml
  parsing:
    - strategy: HtmlParser
      use:
        - Sitemap
        - URL
    - strategy: FileParser
      use:
        - Path
  chunking:
    - strategy: RecursiveTextSplitter
      params:
        chunk_size: 500
  embedding:
    - strategy: OpenAI-Simple
      params:
        model: nomic-embed-text:latest
        api_key: ${API_KEY}
        url: https://chat.agrospai.udl.cat/api/
  benchmarking:
    - strategy: ...
      params:
        test: asdsa
