cache:
  path: ./.fastrag
  lifespan: 1d
steps:
  fetching:
    # - strategy: Path
    #   params:
    #     path: ./resources/test/
    # - strategy: SitemapXML
    #   params:
    #     url: https://agrospai.udl.cat/sitemap.xml
    #     regex:
    #       - https?://[^/]+/docs/
    # - strategy: URL
    #   params:
    #     url: https://agrospai.udl.cat+
    - strategy: Crawling
      params:
        url: https://agrospai.udl.cat
        workers: 5
        depth: 2
  parsing:
    - strategy: HtmlParser
      use:
        - Sitemap
        - URL
    - strategy: FileParser
      use:
        - Path
  chunking:
    - strategy: RecursiveTextSplitter
      params:
        chunk_size: 500
  embedding:
    - strategy: OpenAI-Simple
      params:
        model: nomic-embed-text:latest
        api_key: ${API_KEY}
        url: https://chat.agrospai.udl.cat/api/
  benchmarking:
    - strategy: ...
      params:
        test: asdsa
